spring:
  profiles:
    active: local
    group:
      local:
        - infra-local
        - common-local
        - domain-local
      dev:
        - infra-dev
        - common-dev
        - domain-dev
    include:
      - infra
      - common
      - domain
  mvc:
    static-path-pattern: static/**
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
  web:
    resources:
      static-locations:
        - classpath:/static/
#      add-mappings: true


server:
  shutdown: graceful
  servlet:
    session:
      timeout: 7200

---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      enabled: true
server:
  port: 8080


test-message : local-test
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 80

test-message : dev-test

