naver:
  storage:
    end-point: https://kr.object.ncloudstorage.com
    region-name: kr-standard
    bucket-name: picasso-bucket

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---
spring:
  config:
    activate:
      on-profile: common-local

picasso:
  domain: http://localhost:8080/
---
spring:
  config:
    activate:
      on-profile: common-dev

picasso:
  domain: http://picasso.jong1.com/