Project Picasso{
  database_type: 'MySQL'
  Note: '''
    # Picasso DB스키마 구조
  '''
}

Table Auth.tbl_user [
  headercolor: #E4A62E, note: '사용자 계정 정보 저장 테이블'
] {
  id bigint [pk, not null, increment, note:'사용자 UID']
  email varchar [unique, not null , note: "사용자 로그인 ID"]
  nick_name varchar(255) [not null, note: '사용자 NickName']
  password varchar(255) [not null, note: '패스워드']
  profile varchar(255) [note: "프로필 링크"]
  point long [default: 0, note: "사용자 보유중인 포인트 금액"]
  login_type varchar [
    not null, default: "DEFAULT",
    note: '''
      사용자 회원가입 종류
      - DEFAULT: 기본 사용자 가입
      - KAKAO: 카카오
      - NAVER: 네이버
    '''
  ]
  user_role varchar [
    not null, default: "USER",
    note: '''
      사용자 권한
      - USER: 사용자
      - ADMIN: 관리자
    '''
  ]
  user_status varchar [
    not null,
    note: '''
      가입 방법에 따라 DEFAULT가 달라져야 하기 때문에 DEFAULT를 일부로 부여하지 않음.
      - NOT_ACTIVE: 계정 인증 전
      - ACTIVE: 계정 인증 및 정상 사용 가능
      - SUSPENSION: 계정 정지
      - DELETE: 회원 탈퇴 및 삭제 필요 계정
    '''
  ]
  created_at datetime [not null, default: `now()`, note: '계정 생성일']
  login_at datetime [not null, default: `now()`, note: '마지막 로그인 시간']
}

//--결제
Table Payment.tbl_payment_history [
  headercolor: #24BAB1,
  note: '금액 갱신 히스토리'
] {
  id bigint [pk, increment, note:'PK ID']
  amount bigint [not null, note:'결제 정보']
  user_id bigint [not null, note: '사용자 ID']
  merchant_uid varchar(255) [not null, note: '결제 번호']
  pg_name varchar(255) [not null, note: '''
    - KAKAO : 카카오 결제
    - TOSS  : 토스 결제
  ''']
  product_name varchar(255) [not null, note: '결제 상품 명']
  primary key (id)
}

//---------------------------------------------------------
Table Picture.tbl_picture[
  headercolor: #24BAB1,
  note: '게시물(경매 물품 게시물)'
] {
  picture_id bigint [pk, increment, note: '게시물 ID']
  picture_name varchar [not null, note: '작품명, 게시물 제목']
  painter_name varchar [not null, note: '화가 명']
  detail clob [note: '게시물 내용, 물품에 대한 상세 설명']
  img_url varchar [not null, note: '게시물 이미지 링크']
  increase_amount long [not null, note: "최소 입찰 단위"]
  starting_price long [not null, default: 0, note: "입찰 시작가"]
  size varchar [not null, note: '그림 SIZE']
  picture_status varchar [default: 'BEFORE_APPROVE', note:'''
    게시물 상태
    - BEFORE_APPROVE : 입찰 전(관리자 승인 전)
    - AFTER_APPROVE : 입찰 전(관리자 승인 후)
    - BIDDING : 입찰중
    - REJECT : 경매종료(유찰)
    - SUCCESS_BID : 경매종료(낙찰)

    게시물의 경우 BeforeApprove 상태에서만 수정 가능
  ''']
  user_id bigint [ref:> Auth.tbl_user.id, not null, note:'사용자 ID']
  bid_start_date date [default: `now()`, note: '경매 시작일']
  bid_end_date date [default: `now()`, note: '경매 종료일']
}

Table Picture.tbl_picture_bid_history [
  headercolor: #24BAB1,
  note: '금액 갱신 히스토리'
] {
  id bigint [pk, not null, increment, note: 'PK']
  bid_amount bigint [not null, note: '입찰 희망가']
  created_at datetime [not null, note: '입찰시간']
  picture_id bigint [ref:> Picture.tbl_picture.picture_id ,not null, note: '입찰을 진행한 Picture ID']
  user_id bigint [ref:- Auth.tbl_user.id ,not null, note: '입찰 사용자 ID']
}
//---------------

//사용자 정보 관련 그룹
TableGroup User {
  Auth.tbl_user
  Payment.tbl_payment_history
}

// 게시물 그룹
TableGroup Picture {
  Picture.tbl_picture
  Picture.tbl_picture_bid_history
}

